# Generated by Django 4.2.25 on 2025-10-20 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uems_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
