# Generated by Django 4.2.25 on 2025-10-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uems_app', '0002_event_from_date_event_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='from_date',
            field=models.DateTimeField(default='2025-10-20 00:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_date',
            field=models.DateTimeField(default='2025-10-20 00:00:00'),
        ),
    ]
