# Generated by Django 5.2.7 on 2025-11-01 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uems_app', '0003_alter_event_from_date_alter_event_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
